name: "CI"
on: [push, pull_request]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Setting up BATS
        run: sudo npm install -g bats
        
      - name: Running tests
        run: bats -t -r test/tests.bats
